-- MySQL Script generated by MySQL Workbench
-- Mon Dec  6 21:16:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema webshop_wwi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webshop_wwi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webshop_wwi` DEFAULT CHARACTER SET utf8 ;
USE `webshop_wwi` ;

-- -----------------------------------------------------
-- Table `webshop_wwi`.`attachments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop_wwi`.`attachments` (
  `id` BIGINT NOT NULL,
  `fk_att_product_id` BIGINT NULL,
  `filename` NVARCHAR(512) NULL,
  `file_location` NVARCHAR(512) NULL,
  `minetype` NVARCHAR(512) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_att_product_id_idx` (`fk_att_product_id` ASC) ,
  CONSTRAINT `fk_att_product_id`
    FOREIGN KEY (`fk_att_product_id`)
    REFERENCES `webshop_wwi`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop_wwi`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop_wwi`.`category` (
  `id` BIGINT NOT NULL,
  `category_name` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop_wwi`.`delivery_adress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop_wwi`.`delivery_adress` (
  `id` BIGINT NOT NULL,
  `fk_deladd_user_id` BIGINT NULL,
  `title` VARCHAR(45) NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `organization_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `region` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `street` VARCHAR(45) NULL,
  `street_number` INT NULL,
  `street_additional` VARCHAR(10) NULL,
  `postal_code` VARCHAR(6) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_deladd_user_id_idx` (`fk_deladd_user_id` ASC) ,
  CONSTRAINT `fk_deladd_user_id`
    FOREIGN KEY (`fk_deladd_user_id`)
    REFERENCES `webshop_wwi`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop_wwi`.`order_orderlines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop_wwi`.`order_orderlines` (
  `id` BIGINT NOT NULL,
  `fk_ororlines_order_id` BIGINT NULL,
  `fk_ororlines_orlines_id` BIGINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `orderlines_id_idx` (`fk_ororlines_orlines_id` ASC) ,
  INDEX `fk_ororlines_order_id_idx` (`fk_ororlines_order_id` ASC) ,
  CONSTRAINT `fk_ororlines_order_id`
    FOREIGN KEY (`fk_ororlines_order_id`)
    REFERENCES `webshop_wwi`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ororlines_orlines_id`
    FOREIGN KEY (`fk_ororlines_orlines_id`)
    REFERENCES `webshop_wwi`.`orderlines` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop_wwi`.`orderlines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop_wwi`.`orderlines` (
  `id` BIGINT NOT NULL,
  `fk_orderlines_product_id` BIGINT NULL,
  `quantity` INT NULL,
  `price_amount` INT NULL,
  `price_currency` TEXT NULL,
  `price_precision` INT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `product_id_idx` (`fk_orderlines_product_id` ASC) ,
  CONSTRAINT `fk_orderlines_product_id`
    FOREIGN KEY (`fk_orderlines_product_id`)
    REFERENCES `webshop_wwi`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop_wwi`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop_wwi`.`orders` (
  `id` BIGINT NOT NULL,
  `fk_user_orders_id` BIGINT NULL,
  `delivery_address_id` BIGINT NULL,
  `is_paid` TINYINT NULL,
  `paid_at` TIMESTAMP NULL,
  `total_discount_amount` INT NULL,
  `total_discount_currency` NVARCHAR(512) NULL,
  `total_discount_precision` INT NULL,
  `total_price_amount` INT NULL,
  `total_price_currency` INT NULL,
  `total_price_precision` INT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`fk_user_orders_id` ASC) ,
  CONSTRAINT `fk_user_orders_id`
    FOREIGN KEY (`fk_user_orders_id`)
    REFERENCES `webshop_wwi`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop_wwi`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop_wwi`.`product` (
  `id` BIGINT NOT NULL,
  `product_name` VARCHAR(45) NULL,
  `description` LONGTEXT NULL,
  `stock` INT NULL,
  `price_amount` INT NULL,
  `price_currency` TEXT NULL,
  `price_precision` INT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop_wwi`.`productcategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop_wwi`.`productcategory` (
  `id` BIGINT NOT NULL,
  `fk_prodcat_product_id` BIGINT NULL,
  `fk_prodcat_cat_id` BIGINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `product_id_idx` (`fk_prodcat_product_id` ASC) ,
  INDEX `fk_prodcat_cat_id_idx` (`fk_prodcat_cat_id` ASC) ,
  CONSTRAINT `fk_prodcat_product_id`
    FOREIGN KEY (`fk_prodcat_product_id`)
    REFERENCES `webshop_wwi`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prodcat_cat_id`
    FOREIGN KEY (`fk_prodcat_cat_id`)
    REFERENCES `webshop_wwi`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webshop_wwi`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webshop_wwi`.`users` (
  `id` BIGINT NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phonenumber` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `userrole_id` INT NULL,
  `token` VARCHAR(45) NULL,
  `active` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '	';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
